/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "error.h"
#import "type.h"

@protocol Sns <NSObject>
- (AuthResponse *) login: (Auth *) auth;  // throws UserException *, SystemException *, TException
- (UserInfo *) userInfo_get: (NSString *) accessToken : (int64_t) id;  // throws UserException *, SystemException *, NotFoundException *, TException
- (UserInfo *) userInfo_set: (NSString *) accessToken : (UserInfo *) userInfo;  // throws UserException *, SystemException *, TException
- (EventInfo *) eventInfo_get: (NSString *) accessToken : (int64_t) id;  // throws UserException *, SystemException *, NotFoundException *, TException
- (EventInfo *) eventInfo_set: (NSString *) accessToken : (EventInfo *) eventInfo;  // throws UserException *, SystemException *, TException
- (int64_t) eventPublish: (NSString *) accessToken;  // throws UserException *, SystemException *, TException
- (EventInfo *) eventApply: (NSString *) accessToken : (int64_t) id;  // throws UserException *, SystemException *, NotFoundException *, TException
@end

@interface SnsClient : NSObject <Sns> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface SnsProcessor : NSObject <TProcessor> {
  id <Sns> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithSns: (id <Sns>) service;
- (id<Sns>) service;
@end

@interface serviceConstants : NSObject {
}
@end
