/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


#import "type.h"

@implementation AuthRequest

- (id) initWithClient_id: (int64_t) client_id client_secret: (NSString *) client_secret
{
  self = [super init];
  __client_id = client_id;
  __client_id_isset = YES;
  __client_secret = [client_secret retain];
  __client_secret_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"client_id"])
  {
    __client_id = [decoder decodeInt64ForKey: @"client_id"];
    __client_id_isset = YES;
  }
  if ([decoder containsValueForKey: @"client_secret"])
  {
    __client_secret = [[decoder decodeObjectForKey: @"client_secret"] retain];
    __client_secret_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__client_id_isset)
  {
    [encoder encodeInt64: __client_id forKey: @"client_id"];
  }
  if (__client_secret_isset)
  {
    [encoder encodeObject: __client_secret forKey: @"client_secret"];
  }
}

- (void) dealloc
{
  [__client_secret release];
  [super dealloc];
}

- (int64_t) client_id {
  return __client_id;
}

- (void) setClient_id: (int64_t) client_id {
  __client_id = client_id;
  __client_id_isset = YES;
}

- (BOOL) client_idIsSet {
  return __client_id_isset;
}

- (void) unsetClient_id {
  __client_id_isset = NO;
}

- (NSString *) client_secret {
  return [[__client_secret retain] autorelease];
}

- (void) setClient_secret: (NSString *) client_secret {
  [client_secret retain];
  [__client_secret release];
  __client_secret = client_secret;
  __client_secret_isset = YES;
}

- (BOOL) client_secretIsSet {
  return __client_secret_isset;
}

- (void) unsetClient_secret {
  [__client_secret release];
  __client_secret = nil;
  __client_secret_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setClient_id: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setClient_secret: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"AuthRequest"];
  if (__client_id_isset) {
    [outProtocol writeFieldBeginWithName: @"client_id" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __client_id];
    [outProtocol writeFieldEnd];
  }
  if (__client_secret_isset) {
    if (__client_secret != nil) {
      [outProtocol writeFieldBeginWithName: @"client_secret" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __client_secret];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"AuthRequest("];
  [ms appendString: @"client_id:"];
  [ms appendFormat: @"%qi", __client_id];
  [ms appendString: @",client_secret:"];
  [ms appendFormat: @"\"%@\"", __client_secret];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation AuthResponse

- (id) initWithAccess_token: (NSString *) access_token expire_in: (timestamp) expire_in user_id: (int64_t) user_id
{
  self = [super init];
  __access_token = [access_token retain];
  __access_token_isset = YES;
  __expire_in = expire_in;
  __expire_in_isset = YES;
  __user_id = user_id;
  __user_id_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"access_token"])
  {
    __access_token = [[decoder decodeObjectForKey: @"access_token"] retain];
    __access_token_isset = YES;
  }
  if ([decoder containsValueForKey: @"expire_in"])
  {
    __expire_in = [decoder decodeInt64ForKey: @"expire_in"];
    __expire_in_isset = YES;
  }
  if ([decoder containsValueForKey: @"user_id"])
  {
    __user_id = [decoder decodeInt64ForKey: @"user_id"];
    __user_id_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__access_token_isset)
  {
    [encoder encodeObject: __access_token forKey: @"access_token"];
  }
  if (__expire_in_isset)
  {
    [encoder encodeInt64: __expire_in forKey: @"expire_in"];
  }
  if (__user_id_isset)
  {
    [encoder encodeInt64: __user_id forKey: @"user_id"];
  }
}

- (void) dealloc
{
  [__access_token release];
  [super dealloc];
}

- (NSString *) access_token {
  return [[__access_token retain] autorelease];
}

- (void) setAccess_token: (NSString *) access_token {
  [access_token retain];
  [__access_token release];
  __access_token = access_token;
  __access_token_isset = YES;
}

- (BOOL) access_tokenIsSet {
  return __access_token_isset;
}

- (void) unsetAccess_token {
  [__access_token release];
  __access_token = nil;
  __access_token_isset = NO;
}

- (int64_t) expire_in {
  return __expire_in;
}

- (void) setExpire_in: (int64_t) expire_in {
  __expire_in = expire_in;
  __expire_in_isset = YES;
}

- (BOOL) expire_inIsSet {
  return __expire_in_isset;
}

- (void) unsetExpire_in {
  __expire_in_isset = NO;
}

- (int64_t) user_id {
  return __user_id;
}

- (void) setUser_id: (int64_t) user_id {
  __user_id = user_id;
  __user_id_isset = YES;
}

- (BOOL) user_idIsSet {
  return __user_id_isset;
}

- (void) unsetUser_id {
  __user_id_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setAccess_token: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setExpire_in: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setUser_id: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"AuthResponse"];
  if (__access_token_isset) {
    if (__access_token != nil) {
      [outProtocol writeFieldBeginWithName: @"access_token" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __access_token];
      [outProtocol writeFieldEnd];
    }
  }
  if (__expire_in_isset) {
    [outProtocol writeFieldBeginWithName: @"expire_in" type: TType_I64 fieldID: 2];
    [outProtocol writeI64: __expire_in];
    [outProtocol writeFieldEnd];
  }
  if (__user_id_isset) {
    [outProtocol writeFieldBeginWithName: @"user_id" type: TType_I64 fieldID: 3];
    [outProtocol writeI64: __user_id];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"AuthResponse("];
  [ms appendString: @"access_token:"];
  [ms appendFormat: @"\"%@\"", __access_token];
  [ms appendString: @",expire_in:"];
  [ms appendFormat: @"%qi", __expire_in];
  [ms appendString: @",user_id:"];
  [ms appendFormat: @"%qi", __user_id];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation UserBasic

- (id) initWithId: (int64_t) id name: (NSString *) name gender: (int) gender org: (NSString *) org job: (NSString *) job avator: (NSString *) avator
{
  self = [super init];
  __id = id;
  __id_isset = YES;
  __name = [name retain];
  __name_isset = YES;
  __gender = gender;
  __gender_isset = YES;
  __org = [org retain];
  __org_isset = YES;
  __job = [job retain];
  __job_isset = YES;
  __avator = [avator retain];
  __avator_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"id"])
  {
    __id = [decoder decodeInt64ForKey: @"id"];
    __id_isset = YES;
  }
  if ([decoder containsValueForKey: @"name"])
  {
    __name = [[decoder decodeObjectForKey: @"name"] retain];
    __name_isset = YES;
  }
  if ([decoder containsValueForKey: @"gender"])
  {
    __gender = [decoder decodeIntForKey: @"gender"];
    __gender_isset = YES;
  }
  if ([decoder containsValueForKey: @"org"])
  {
    __org = [[decoder decodeObjectForKey: @"org"] retain];
    __org_isset = YES;
  }
  if ([decoder containsValueForKey: @"job"])
  {
    __job = [[decoder decodeObjectForKey: @"job"] retain];
    __job_isset = YES;
  }
  if ([decoder containsValueForKey: @"avator"])
  {
    __avator = [[decoder decodeObjectForKey: @"avator"] retain];
    __avator_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__id_isset)
  {
    [encoder encodeInt64: __id forKey: @"id"];
  }
  if (__name_isset)
  {
    [encoder encodeObject: __name forKey: @"name"];
  }
  if (__gender_isset)
  {
    [encoder encodeInt: __gender forKey: @"gender"];
  }
  if (__org_isset)
  {
    [encoder encodeObject: __org forKey: @"org"];
  }
  if (__job_isset)
  {
    [encoder encodeObject: __job forKey: @"job"];
  }
  if (__avator_isset)
  {
    [encoder encodeObject: __avator forKey: @"avator"];
  }
}

- (void) dealloc
{
  [__name release];
  [__org release];
  [__job release];
  [__avator release];
  [super dealloc];
}

- (int64_t) id {
  return __id;
}

- (void) setId: (int64_t) id {
  __id = id;
  __id_isset = YES;
}

- (BOOL) idIsSet {
  return __id_isset;
}

- (void) unsetId {
  __id_isset = NO;
}

- (NSString *) name {
  return [[__name retain] autorelease];
}

- (void) setName: (NSString *) name {
  [name retain];
  [__name release];
  __name = name;
  __name_isset = YES;
}

- (BOOL) nameIsSet {
  return __name_isset;
}

- (void) unsetName {
  [__name release];
  __name = nil;
  __name_isset = NO;
}

- (int) gender {
  return __gender;
}

- (void) setGender: (int) gender {
  __gender = gender;
  __gender_isset = YES;
}

- (BOOL) genderIsSet {
  return __gender_isset;
}

- (void) unsetGender {
  __gender_isset = NO;
}

- (NSString *) org {
  return [[__org retain] autorelease];
}

- (void) setOrg: (NSString *) org {
  [org retain];
  [__org release];
  __org = org;
  __org_isset = YES;
}

- (BOOL) orgIsSet {
  return __org_isset;
}

- (void) unsetOrg {
  [__org release];
  __org = nil;
  __org_isset = NO;
}

- (NSString *) job {
  return [[__job retain] autorelease];
}

- (void) setJob: (NSString *) job {
  [job retain];
  [__job release];
  __job = job;
  __job_isset = YES;
}

- (BOOL) jobIsSet {
  return __job_isset;
}

- (void) unsetJob {
  [__job release];
  __job = nil;
  __job_isset = NO;
}

- (NSString *) avator {
  return [[__avator retain] autorelease];
}

- (void) setAvator: (NSString *) avator {
  [avator retain];
  [__avator release];
  __avator = avator;
  __avator_isset = YES;
}

- (BOOL) avatorIsSet {
  return __avator_isset;
}

- (void) unsetAvator {
  [__avator release];
  __avator = nil;
  __avator_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I32) {
          int fieldValue = [inProtocol readI32];
          [self setGender: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setOrg: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setJob: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 6:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setAvator: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"UserBasic"];
  if (__id_isset) {
    [outProtocol writeFieldBeginWithName: @"id" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __id];
    [outProtocol writeFieldEnd];
  }
  if (__name_isset) {
    if (__name != nil) {
      [outProtocol writeFieldBeginWithName: @"name" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __name];
      [outProtocol writeFieldEnd];
    }
  }
  if (__gender_isset) {
    [outProtocol writeFieldBeginWithName: @"gender" type: TType_I32 fieldID: 3];
    [outProtocol writeI32: __gender];
    [outProtocol writeFieldEnd];
  }
  if (__org_isset) {
    if (__org != nil) {
      [outProtocol writeFieldBeginWithName: @"org" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __org];
      [outProtocol writeFieldEnd];
    }
  }
  if (__job_isset) {
    if (__job != nil) {
      [outProtocol writeFieldBeginWithName: @"job" type: TType_STRING fieldID: 5];
      [outProtocol writeString: __job];
      [outProtocol writeFieldEnd];
    }
  }
  if (__avator_isset) {
    if (__avator != nil) {
      [outProtocol writeFieldBeginWithName: @"avator" type: TType_STRING fieldID: 6];
      [outProtocol writeString: __avator];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"UserBasic("];
  [ms appendString: @"id:"];
  [ms appendFormat: @"%qi", __id];
  [ms appendString: @",name:"];
  [ms appendFormat: @"\"%@\"", __name];
  [ms appendString: @",gender:"];
  [ms appendFormat: @"%i", __gender];
  [ms appendString: @",org:"];
  [ms appendFormat: @"\"%@\"", __org];
  [ms appendString: @",job:"];
  [ms appendFormat: @"\"%@\"", __job];
  [ms appendString: @",avator:"];
  [ms appendFormat: @"\"%@\"", __avator];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation UserExt

- (id) initWithIntro: (NSString *) intro following: (NSArray *) following followed: (NSArray *) followed
{
  self = [super init];
  __intro = [intro retain];
  __intro_isset = YES;
  __following = [following retain];
  __following_isset = YES;
  __followed = [followed retain];
  __followed_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"intro"])
  {
    __intro = [[decoder decodeObjectForKey: @"intro"] retain];
    __intro_isset = YES;
  }
  if ([decoder containsValueForKey: @"following"])
  {
    __following = [[decoder decodeObjectForKey: @"following"] retain];
    __following_isset = YES;
  }
  if ([decoder containsValueForKey: @"followed"])
  {
    __followed = [[decoder decodeObjectForKey: @"followed"] retain];
    __followed_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__intro_isset)
  {
    [encoder encodeObject: __intro forKey: @"intro"];
  }
  if (__following_isset)
  {
    [encoder encodeObject: __following forKey: @"following"];
  }
  if (__followed_isset)
  {
    [encoder encodeObject: __followed forKey: @"followed"];
  }
}

- (void) dealloc
{
  [__intro release];
  [__following release];
  [__followed release];
  [super dealloc];
}

- (NSString *) intro {
  return [[__intro retain] autorelease];
}

- (void) setIntro: (NSString *) intro {
  [intro retain];
  [__intro release];
  __intro = intro;
  __intro_isset = YES;
}

- (BOOL) introIsSet {
  return __intro_isset;
}

- (void) unsetIntro {
  [__intro release];
  __intro = nil;
  __intro_isset = NO;
}

- (NSArray *) following {
  return [[__following retain] autorelease];
}

- (void) setFollowing: (NSArray *) following {
  [following retain];
  [__following release];
  __following = following;
  __following_isset = YES;
}

- (BOOL) followingIsSet {
  return __following_isset;
}

- (void) unsetFollowing {
  [__following release];
  __following = nil;
  __following_isset = NO;
}

- (NSArray *) followed {
  return [[__followed retain] autorelease];
}

- (void) setFollowed: (NSArray *) followed {
  [followed retain];
  [__followed release];
  __followed = followed;
  __followed_isset = YES;
}

- (BOOL) followedIsSet {
  return __followed_isset;
}

- (void) unsetFollowed {
  [__followed release];
  __followed = nil;
  __followed_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setIntro: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_LIST) {
          int _size0;
          [inProtocol readListBeginReturningElementType: NULL size: &_size0];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size0];
          int _i1;
          for (_i1 = 0; _i1 < _size0; ++_i1)
          {
            int64_t _elem2 = [inProtocol readI64];
            [fieldValue addObject: [NSNumber numberWithLongLong: _elem2]];
          }
          [inProtocol readListEnd];
          [self setFollowing: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_LIST) {
          int _size3;
          [inProtocol readListBeginReturningElementType: NULL size: &_size3];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size3];
          int _i4;
          for (_i4 = 0; _i4 < _size3; ++_i4)
          {
            int64_t _elem5 = [inProtocol readI64];
            [fieldValue addObject: [NSNumber numberWithLongLong: _elem5]];
          }
          [inProtocol readListEnd];
          [self setFollowed: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"UserExt"];
  if (__intro_isset) {
    if (__intro != nil) {
      [outProtocol writeFieldBeginWithName: @"intro" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __intro];
      [outProtocol writeFieldEnd];
    }
  }
  if (__following_isset) {
    if (__following != nil) {
      [outProtocol writeFieldBeginWithName: @"following" type: TType_LIST fieldID: 2];
      {
        [outProtocol writeListBeginWithElementType: TType_I64 size: [__following count]];
        int i7;
        for (i7 = 0; i7 < [__following count]; i7++)
        {
          [outProtocol writeI64: [[__following objectAtIndex: i7] longLongValue]];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  if (__followed_isset) {
    if (__followed != nil) {
      [outProtocol writeFieldBeginWithName: @"followed" type: TType_LIST fieldID: 3];
      {
        [outProtocol writeListBeginWithElementType: TType_I64 size: [__followed count]];
        int i9;
        for (i9 = 0; i9 < [__followed count]; i9++)
        {
          [outProtocol writeI64: [[__followed objectAtIndex: i9] longLongValue]];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"UserExt("];
  [ms appendString: @"intro:"];
  [ms appendFormat: @"\"%@\"", __intro];
  [ms appendString: @",following:"];
  [ms appendFormat: @"%@", __following];
  [ms appendString: @",followed:"];
  [ms appendFormat: @"%@", __followed];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation User

- (id) initWithBasic: (UserBasic *) basic ext: (UserExt *) ext
{
  self = [super init];
  __basic = [basic retain];
  __basic_isset = YES;
  __ext = [ext retain];
  __ext_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"basic"])
  {
    __basic = [[decoder decodeObjectForKey: @"basic"] retain];
    __basic_isset = YES;
  }
  if ([decoder containsValueForKey: @"ext"])
  {
    __ext = [[decoder decodeObjectForKey: @"ext"] retain];
    __ext_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__basic_isset)
  {
    [encoder encodeObject: __basic forKey: @"basic"];
  }
  if (__ext_isset)
  {
    [encoder encodeObject: __ext forKey: @"ext"];
  }
}

- (void) dealloc
{
  [__basic release];
  [__ext release];
  [super dealloc];
}

- (UserBasic *) basic {
  return [[__basic retain] autorelease];
}

- (void) setBasic: (UserBasic *) basic {
  [basic retain];
  [__basic release];
  __basic = basic;
  __basic_isset = YES;
}

- (BOOL) basicIsSet {
  return __basic_isset;
}

- (void) unsetBasic {
  [__basic release];
  __basic = nil;
  __basic_isset = NO;
}

- (UserExt *) ext {
  return [[__ext retain] autorelease];
}

- (void) setExt: (UserExt *) ext {
  [ext retain];
  [__ext release];
  __ext = ext;
  __ext_isset = YES;
}

- (BOOL) extIsSet {
  return __ext_isset;
}

- (void) unsetExt {
  [__ext release];
  __ext = nil;
  __ext_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          UserBasic *fieldValue = [[UserBasic alloc] init];
          [fieldValue read: inProtocol];
          [self setBasic: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRUCT) {
          UserExt *fieldValue = [[UserExt alloc] init];
          [fieldValue read: inProtocol];
          [self setExt: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"User"];
  if (__basic_isset) {
    if (__basic != nil) {
      [outProtocol writeFieldBeginWithName: @"basic" type: TType_STRUCT fieldID: 1];
      [__basic write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  if (__ext_isset) {
    if (__ext != nil) {
      [outProtocol writeFieldBeginWithName: @"ext" type: TType_STRUCT fieldID: 2];
      [__ext write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"User("];
  [ms appendString: @"basic:"];
  [ms appendFormat: @"%@", __basic];
  [ms appendString: @",ext:"];
  [ms appendFormat: @"%@", __ext];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation TaskFilter

- (id) initWithSort: (int) sort state: (int) state city_id: (int64_t) city_id tag_id: (int64_t) tag_id distance: (int64_t) distance sponsor_gender: (int) sponsor_gender level: (int64_t) level reward: (BOOL) reward reward_cent: (int64_t) reward_cent
{
  self = [super init];
  __sort = sort;
  __sort_isset = YES;
  __state = state;
  __state_isset = YES;
  __city_id = city_id;
  __city_id_isset = YES;
  __tag_id = tag_id;
  __tag_id_isset = YES;
  __distance = distance;
  __distance_isset = YES;
  __sponsor_gender = sponsor_gender;
  __sponsor_gender_isset = YES;
  __level = level;
  __level_isset = YES;
  __reward = reward;
  __reward_isset = YES;
  __reward_cent = reward_cent;
  __reward_cent_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"sort"])
  {
    __sort = [decoder decodeIntForKey: @"sort"];
    __sort_isset = YES;
  }
  if ([decoder containsValueForKey: @"state"])
  {
    __state = [decoder decodeIntForKey: @"state"];
    __state_isset = YES;
  }
  if ([decoder containsValueForKey: @"city_id"])
  {
    __city_id = [decoder decodeInt64ForKey: @"city_id"];
    __city_id_isset = YES;
  }
  if ([decoder containsValueForKey: @"tag_id"])
  {
    __tag_id = [decoder decodeInt64ForKey: @"tag_id"];
    __tag_id_isset = YES;
  }
  if ([decoder containsValueForKey: @"distance"])
  {
    __distance = [decoder decodeInt64ForKey: @"distance"];
    __distance_isset = YES;
  }
  if ([decoder containsValueForKey: @"sponsor_gender"])
  {
    __sponsor_gender = [decoder decodeIntForKey: @"sponsor_gender"];
    __sponsor_gender_isset = YES;
  }
  if ([decoder containsValueForKey: @"level"])
  {
    __level = [decoder decodeInt64ForKey: @"level"];
    __level_isset = YES;
  }
  if ([decoder containsValueForKey: @"reward"])
  {
    __reward = [decoder decodeBoolForKey: @"reward"];
    __reward_isset = YES;
  }
  if ([decoder containsValueForKey: @"reward_cent"])
  {
    __reward_cent = [decoder decodeInt64ForKey: @"reward_cent"];
    __reward_cent_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__sort_isset)
  {
    [encoder encodeInt: __sort forKey: @"sort"];
  }
  if (__state_isset)
  {
    [encoder encodeInt: __state forKey: @"state"];
  }
  if (__city_id_isset)
  {
    [encoder encodeInt64: __city_id forKey: @"city_id"];
  }
  if (__tag_id_isset)
  {
    [encoder encodeInt64: __tag_id forKey: @"tag_id"];
  }
  if (__distance_isset)
  {
    [encoder encodeInt64: __distance forKey: @"distance"];
  }
  if (__sponsor_gender_isset)
  {
    [encoder encodeInt: __sponsor_gender forKey: @"sponsor_gender"];
  }
  if (__level_isset)
  {
    [encoder encodeInt64: __level forKey: @"level"];
  }
  if (__reward_isset)
  {
    [encoder encodeBool: __reward forKey: @"reward"];
  }
  if (__reward_cent_isset)
  {
    [encoder encodeInt64: __reward_cent forKey: @"reward_cent"];
  }
}

- (void) dealloc
{
  [super dealloc];
}

- (int) sort {
  return __sort;
}

- (void) setSort: (int) sort {
  __sort = sort;
  __sort_isset = YES;
}

- (BOOL) sortIsSet {
  return __sort_isset;
}

- (void) unsetSort {
  __sort_isset = NO;
}

- (int) state {
  return __state;
}

- (void) setState: (int) state {
  __state = state;
  __state_isset = YES;
}

- (BOOL) stateIsSet {
  return __state_isset;
}

- (void) unsetState {
  __state_isset = NO;
}

- (int64_t) city_id {
  return __city_id;
}

- (void) setCity_id: (int64_t) city_id {
  __city_id = city_id;
  __city_id_isset = YES;
}

- (BOOL) city_idIsSet {
  return __city_id_isset;
}

- (void) unsetCity_id {
  __city_id_isset = NO;
}

- (int64_t) tag_id {
  return __tag_id;
}

- (void) setTag_id: (int64_t) tag_id {
  __tag_id = tag_id;
  __tag_id_isset = YES;
}

- (BOOL) tag_idIsSet {
  return __tag_id_isset;
}

- (void) unsetTag_id {
  __tag_id_isset = NO;
}

- (int64_t) distance {
  return __distance;
}

- (void) setDistance: (int64_t) distance {
  __distance = distance;
  __distance_isset = YES;
}

- (BOOL) distanceIsSet {
  return __distance_isset;
}

- (void) unsetDistance {
  __distance_isset = NO;
}

- (int) sponsor_gender {
  return __sponsor_gender;
}

- (void) setSponsor_gender: (int) sponsor_gender {
  __sponsor_gender = sponsor_gender;
  __sponsor_gender_isset = YES;
}

- (BOOL) sponsor_genderIsSet {
  return __sponsor_gender_isset;
}

- (void) unsetSponsor_gender {
  __sponsor_gender_isset = NO;
}

- (int64_t) level {
  return __level;
}

- (void) setLevel: (int64_t) level {
  __level = level;
  __level_isset = YES;
}

- (BOOL) levelIsSet {
  return __level_isset;
}

- (void) unsetLevel {
  __level_isset = NO;
}

- (BOOL) reward {
  return __reward;
}

- (void) setReward: (BOOL) reward {
  __reward = reward;
  __reward_isset = YES;
}

- (BOOL) rewardIsSet {
  return __reward_isset;
}

- (void) unsetReward {
  __reward_isset = NO;
}

- (int64_t) reward_cent {
  return __reward_cent;
}

- (void) setReward_cent: (int64_t) reward_cent {
  __reward_cent = reward_cent;
  __reward_cent_isset = YES;
}

- (BOOL) reward_centIsSet {
  return __reward_cent_isset;
}

- (void) unsetReward_cent {
  __reward_cent_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int fieldValue = [inProtocol readI32];
          [self setSort: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I32) {
          int fieldValue = [inProtocol readI32];
          [self setState: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setCity_id: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setTag_id: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setDistance: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 6:
        if (fieldType == TType_I32) {
          int fieldValue = [inProtocol readI32];
          [self setSponsor_gender: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 7:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setLevel: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 8:
        if (fieldType == TType_BOOL) {
          BOOL fieldValue = [inProtocol readBool];
          [self setReward: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 9:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setReward_cent: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"TaskFilter"];
  if (__sort_isset) {
    [outProtocol writeFieldBeginWithName: @"sort" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __sort];
    [outProtocol writeFieldEnd];
  }
  if (__state_isset) {
    [outProtocol writeFieldBeginWithName: @"state" type: TType_I32 fieldID: 2];
    [outProtocol writeI32: __state];
    [outProtocol writeFieldEnd];
  }
  if (__city_id_isset) {
    [outProtocol writeFieldBeginWithName: @"city_id" type: TType_I64 fieldID: 3];
    [outProtocol writeI64: __city_id];
    [outProtocol writeFieldEnd];
  }
  if (__tag_id_isset) {
    [outProtocol writeFieldBeginWithName: @"tag_id" type: TType_I64 fieldID: 4];
    [outProtocol writeI64: __tag_id];
    [outProtocol writeFieldEnd];
  }
  if (__distance_isset) {
    [outProtocol writeFieldBeginWithName: @"distance" type: TType_I64 fieldID: 5];
    [outProtocol writeI64: __distance];
    [outProtocol writeFieldEnd];
  }
  if (__sponsor_gender_isset) {
    [outProtocol writeFieldBeginWithName: @"sponsor_gender" type: TType_I32 fieldID: 6];
    [outProtocol writeI32: __sponsor_gender];
    [outProtocol writeFieldEnd];
  }
  if (__level_isset) {
    [outProtocol writeFieldBeginWithName: @"level" type: TType_I64 fieldID: 7];
    [outProtocol writeI64: __level];
    [outProtocol writeFieldEnd];
  }
  if (__reward_isset) {
    [outProtocol writeFieldBeginWithName: @"reward" type: TType_BOOL fieldID: 8];
    [outProtocol writeBool: __reward];
    [outProtocol writeFieldEnd];
  }
  if (__reward_cent_isset) {
    [outProtocol writeFieldBeginWithName: @"reward_cent" type: TType_I64 fieldID: 9];
    [outProtocol writeI64: __reward_cent];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"TaskFilter("];
  [ms appendString: @"sort:"];
  [ms appendFormat: @"%i", __sort];
  [ms appendString: @",state:"];
  [ms appendFormat: @"%i", __state];
  [ms appendString: @",city_id:"];
  [ms appendFormat: @"%qi", __city_id];
  [ms appendString: @",tag_id:"];
  [ms appendFormat: @"%qi", __tag_id];
  [ms appendString: @",distance:"];
  [ms appendFormat: @"%qi", __distance];
  [ms appendString: @",sponsor_gender:"];
  [ms appendFormat: @"%i", __sponsor_gender];
  [ms appendString: @",level:"];
  [ms appendFormat: @"%qi", __level];
  [ms appendString: @",reward:"];
  [ms appendFormat: @"%i", __reward];
  [ms appendString: @",reward_cent:"];
  [ms appendFormat: @"%qi", __reward_cent];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation TaskBasic

- (id) initWithId: (int64_t) id name: (NSString *) name sponsor: (int64_t) sponsor tag_id: (int64_t) tag_id intro: (NSString *) intro state: (int) state area_id: (int64_t) area_id address: (NSString *) address end_time: (timestamp) end_time reward: (NSString *) reward reward_cent: (int64_t) reward_cent apply_count: (int64_t) apply_count invite_count: (int64_t) invite_count accept_count: (int64_t) accept_count
{
  self = [super init];
  __id = id;
  __id_isset = YES;
  __name = [name retain];
  __name_isset = YES;
  __sponsor = sponsor;
  __sponsor_isset = YES;
  __tag_id = tag_id;
  __tag_id_isset = YES;
  __intro = [intro retain];
  __intro_isset = YES;
  __state = state;
  __state_isset = YES;
  __area_id = area_id;
  __area_id_isset = YES;
  __address = [address retain];
  __address_isset = YES;
  __end_time = end_time;
  __end_time_isset = YES;
  __reward = [reward retain];
  __reward_isset = YES;
  __reward_cent = reward_cent;
  __reward_cent_isset = YES;
  __apply_count = apply_count;
  __apply_count_isset = YES;
  __invite_count = invite_count;
  __invite_count_isset = YES;
  __accept_count = accept_count;
  __accept_count_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"id"])
  {
    __id = [decoder decodeInt64ForKey: @"id"];
    __id_isset = YES;
  }
  if ([decoder containsValueForKey: @"name"])
  {
    __name = [[decoder decodeObjectForKey: @"name"] retain];
    __name_isset = YES;
  }
  if ([decoder containsValueForKey: @"sponsor"])
  {
    __sponsor = [decoder decodeInt64ForKey: @"sponsor"];
    __sponsor_isset = YES;
  }
  if ([decoder containsValueForKey: @"tag_id"])
  {
    __tag_id = [decoder decodeInt64ForKey: @"tag_id"];
    __tag_id_isset = YES;
  }
  if ([decoder containsValueForKey: @"intro"])
  {
    __intro = [[decoder decodeObjectForKey: @"intro"] retain];
    __intro_isset = YES;
  }
  if ([decoder containsValueForKey: @"state"])
  {
    __state = [decoder decodeIntForKey: @"state"];
    __state_isset = YES;
  }
  if ([decoder containsValueForKey: @"area_id"])
  {
    __area_id = [decoder decodeInt64ForKey: @"area_id"];
    __area_id_isset = YES;
  }
  if ([decoder containsValueForKey: @"address"])
  {
    __address = [[decoder decodeObjectForKey: @"address"] retain];
    __address_isset = YES;
  }
  if ([decoder containsValueForKey: @"end_time"])
  {
    __end_time = [decoder decodeInt64ForKey: @"end_time"];
    __end_time_isset = YES;
  }
  if ([decoder containsValueForKey: @"reward"])
  {
    __reward = [[decoder decodeObjectForKey: @"reward"] retain];
    __reward_isset = YES;
  }
  if ([decoder containsValueForKey: @"reward_cent"])
  {
    __reward_cent = [decoder decodeInt64ForKey: @"reward_cent"];
    __reward_cent_isset = YES;
  }
  if ([decoder containsValueForKey: @"apply_count"])
  {
    __apply_count = [decoder decodeInt64ForKey: @"apply_count"];
    __apply_count_isset = YES;
  }
  if ([decoder containsValueForKey: @"invite_count"])
  {
    __invite_count = [decoder decodeInt64ForKey: @"invite_count"];
    __invite_count_isset = YES;
  }
  if ([decoder containsValueForKey: @"accept_count"])
  {
    __accept_count = [decoder decodeInt64ForKey: @"accept_count"];
    __accept_count_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__id_isset)
  {
    [encoder encodeInt64: __id forKey: @"id"];
  }
  if (__name_isset)
  {
    [encoder encodeObject: __name forKey: @"name"];
  }
  if (__sponsor_isset)
  {
    [encoder encodeInt64: __sponsor forKey: @"sponsor"];
  }
  if (__tag_id_isset)
  {
    [encoder encodeInt64: __tag_id forKey: @"tag_id"];
  }
  if (__intro_isset)
  {
    [encoder encodeObject: __intro forKey: @"intro"];
  }
  if (__state_isset)
  {
    [encoder encodeInt: __state forKey: @"state"];
  }
  if (__area_id_isset)
  {
    [encoder encodeInt64: __area_id forKey: @"area_id"];
  }
  if (__address_isset)
  {
    [encoder encodeObject: __address forKey: @"address"];
  }
  if (__end_time_isset)
  {
    [encoder encodeInt64: __end_time forKey: @"end_time"];
  }
  if (__reward_isset)
  {
    [encoder encodeObject: __reward forKey: @"reward"];
  }
  if (__reward_cent_isset)
  {
    [encoder encodeInt64: __reward_cent forKey: @"reward_cent"];
  }
  if (__apply_count_isset)
  {
    [encoder encodeInt64: __apply_count forKey: @"apply_count"];
  }
  if (__invite_count_isset)
  {
    [encoder encodeInt64: __invite_count forKey: @"invite_count"];
  }
  if (__accept_count_isset)
  {
    [encoder encodeInt64: __accept_count forKey: @"accept_count"];
  }
}

- (void) dealloc
{
  [__name release];
  [__intro release];
  [__address release];
  [__reward release];
  [super dealloc];
}

- (int64_t) id {
  return __id;
}

- (void) setId: (int64_t) id {
  __id = id;
  __id_isset = YES;
}

- (BOOL) idIsSet {
  return __id_isset;
}

- (void) unsetId {
  __id_isset = NO;
}

- (NSString *) name {
  return [[__name retain] autorelease];
}

- (void) setName: (NSString *) name {
  [name retain];
  [__name release];
  __name = name;
  __name_isset = YES;
}

- (BOOL) nameIsSet {
  return __name_isset;
}

- (void) unsetName {
  [__name release];
  __name = nil;
  __name_isset = NO;
}

- (int64_t) sponsor {
  return __sponsor;
}

- (void) setSponsor: (int64_t) sponsor {
  __sponsor = sponsor;
  __sponsor_isset = YES;
}

- (BOOL) sponsorIsSet {
  return __sponsor_isset;
}

- (void) unsetSponsor {
  __sponsor_isset = NO;
}

- (int64_t) tag_id {
  return __tag_id;
}

- (void) setTag_id: (int64_t) tag_id {
  __tag_id = tag_id;
  __tag_id_isset = YES;
}

- (BOOL) tag_idIsSet {
  return __tag_id_isset;
}

- (void) unsetTag_id {
  __tag_id_isset = NO;
}

- (NSString *) intro {
  return [[__intro retain] autorelease];
}

- (void) setIntro: (NSString *) intro {
  [intro retain];
  [__intro release];
  __intro = intro;
  __intro_isset = YES;
}

- (BOOL) introIsSet {
  return __intro_isset;
}

- (void) unsetIntro {
  [__intro release];
  __intro = nil;
  __intro_isset = NO;
}

- (int) state {
  return __state;
}

- (void) setState: (int) state {
  __state = state;
  __state_isset = YES;
}

- (BOOL) stateIsSet {
  return __state_isset;
}

- (void) unsetState {
  __state_isset = NO;
}

- (int64_t) area_id {
  return __area_id;
}

- (void) setArea_id: (int64_t) area_id {
  __area_id = area_id;
  __area_id_isset = YES;
}

- (BOOL) area_idIsSet {
  return __area_id_isset;
}

- (void) unsetArea_id {
  __area_id_isset = NO;
}

- (NSString *) address {
  return [[__address retain] autorelease];
}

- (void) setAddress: (NSString *) address {
  [address retain];
  [__address release];
  __address = address;
  __address_isset = YES;
}

- (BOOL) addressIsSet {
  return __address_isset;
}

- (void) unsetAddress {
  [__address release];
  __address = nil;
  __address_isset = NO;
}

- (int64_t) end_time {
  return __end_time;
}

- (void) setEnd_time: (int64_t) end_time {
  __end_time = end_time;
  __end_time_isset = YES;
}

- (BOOL) end_timeIsSet {
  return __end_time_isset;
}

- (void) unsetEnd_time {
  __end_time_isset = NO;
}

- (NSString *) reward {
  return [[__reward retain] autorelease];
}

- (void) setReward: (NSString *) reward {
  [reward retain];
  [__reward release];
  __reward = reward;
  __reward_isset = YES;
}

- (BOOL) rewardIsSet {
  return __reward_isset;
}

- (void) unsetReward {
  [__reward release];
  __reward = nil;
  __reward_isset = NO;
}

- (int64_t) reward_cent {
  return __reward_cent;
}

- (void) setReward_cent: (int64_t) reward_cent {
  __reward_cent = reward_cent;
  __reward_cent_isset = YES;
}

- (BOOL) reward_centIsSet {
  return __reward_cent_isset;
}

- (void) unsetReward_cent {
  __reward_cent_isset = NO;
}

- (int64_t) apply_count {
  return __apply_count;
}

- (void) setApply_count: (int64_t) apply_count {
  __apply_count = apply_count;
  __apply_count_isset = YES;
}

- (BOOL) apply_countIsSet {
  return __apply_count_isset;
}

- (void) unsetApply_count {
  __apply_count_isset = NO;
}

- (int64_t) invite_count {
  return __invite_count;
}

- (void) setInvite_count: (int64_t) invite_count {
  __invite_count = invite_count;
  __invite_count_isset = YES;
}

- (BOOL) invite_countIsSet {
  return __invite_count_isset;
}

- (void) unsetInvite_count {
  __invite_count_isset = NO;
}

- (int64_t) accept_count {
  return __accept_count;
}

- (void) setAccept_count: (int64_t) accept_count {
  __accept_count = accept_count;
  __accept_count_isset = YES;
}

- (BOOL) accept_countIsSet {
  return __accept_count_isset;
}

- (void) unsetAccept_count {
  __accept_count_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setSponsor: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setTag_id: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setIntro: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 6:
        if (fieldType == TType_I32) {
          int fieldValue = [inProtocol readI32];
          [self setState: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 7:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setArea_id: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 8:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setAddress: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 9:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setEnd_time: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 10:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setReward: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 11:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setReward_cent: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 12:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setApply_count: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 13:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setInvite_count: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 14:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setAccept_count: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"TaskBasic"];
  if (__id_isset) {
    [outProtocol writeFieldBeginWithName: @"id" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __id];
    [outProtocol writeFieldEnd];
  }
  if (__name_isset) {
    if (__name != nil) {
      [outProtocol writeFieldBeginWithName: @"name" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __name];
      [outProtocol writeFieldEnd];
    }
  }
  if (__sponsor_isset) {
    [outProtocol writeFieldBeginWithName: @"sponsor" type: TType_I64 fieldID: 3];
    [outProtocol writeI64: __sponsor];
    [outProtocol writeFieldEnd];
  }
  if (__tag_id_isset) {
    [outProtocol writeFieldBeginWithName: @"tag_id" type: TType_I64 fieldID: 4];
    [outProtocol writeI64: __tag_id];
    [outProtocol writeFieldEnd];
  }
  if (__intro_isset) {
    if (__intro != nil) {
      [outProtocol writeFieldBeginWithName: @"intro" type: TType_STRING fieldID: 5];
      [outProtocol writeString: __intro];
      [outProtocol writeFieldEnd];
    }
  }
  if (__state_isset) {
    [outProtocol writeFieldBeginWithName: @"state" type: TType_I32 fieldID: 6];
    [outProtocol writeI32: __state];
    [outProtocol writeFieldEnd];
  }
  if (__area_id_isset) {
    [outProtocol writeFieldBeginWithName: @"area_id" type: TType_I64 fieldID: 7];
    [outProtocol writeI64: __area_id];
    [outProtocol writeFieldEnd];
  }
  if (__address_isset) {
    if (__address != nil) {
      [outProtocol writeFieldBeginWithName: @"address" type: TType_STRING fieldID: 8];
      [outProtocol writeString: __address];
      [outProtocol writeFieldEnd];
    }
  }
  if (__end_time_isset) {
    [outProtocol writeFieldBeginWithName: @"end_time" type: TType_I64 fieldID: 9];
    [outProtocol writeI64: __end_time];
    [outProtocol writeFieldEnd];
  }
  if (__reward_isset) {
    if (__reward != nil) {
      [outProtocol writeFieldBeginWithName: @"reward" type: TType_STRING fieldID: 10];
      [outProtocol writeString: __reward];
      [outProtocol writeFieldEnd];
    }
  }
  if (__reward_cent_isset) {
    [outProtocol writeFieldBeginWithName: @"reward_cent" type: TType_I64 fieldID: 11];
    [outProtocol writeI64: __reward_cent];
    [outProtocol writeFieldEnd];
  }
  if (__apply_count_isset) {
    [outProtocol writeFieldBeginWithName: @"apply_count" type: TType_I64 fieldID: 12];
    [outProtocol writeI64: __apply_count];
    [outProtocol writeFieldEnd];
  }
  if (__invite_count_isset) {
    [outProtocol writeFieldBeginWithName: @"invite_count" type: TType_I64 fieldID: 13];
    [outProtocol writeI64: __invite_count];
    [outProtocol writeFieldEnd];
  }
  if (__accept_count_isset) {
    [outProtocol writeFieldBeginWithName: @"accept_count" type: TType_I64 fieldID: 14];
    [outProtocol writeI64: __accept_count];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"TaskBasic("];
  [ms appendString: @"id:"];
  [ms appendFormat: @"%qi", __id];
  [ms appendString: @",name:"];
  [ms appendFormat: @"\"%@\"", __name];
  [ms appendString: @",sponsor:"];
  [ms appendFormat: @"%qi", __sponsor];
  [ms appendString: @",tag_id:"];
  [ms appendFormat: @"%qi", __tag_id];
  [ms appendString: @",intro:"];
  [ms appendFormat: @"\"%@\"", __intro];
  [ms appendString: @",state:"];
  [ms appendFormat: @"%i", __state];
  [ms appendString: @",area_id:"];
  [ms appendFormat: @"%qi", __area_id];
  [ms appendString: @",address:"];
  [ms appendFormat: @"\"%@\"", __address];
  [ms appendString: @",end_time:"];
  [ms appendFormat: @"%qi", __end_time];
  [ms appendString: @",reward:"];
  [ms appendFormat: @"\"%@\"", __reward];
  [ms appendString: @",reward_cent:"];
  [ms appendFormat: @"%qi", __reward_cent];
  [ms appendString: @",apply_count:"];
  [ms appendFormat: @"%qi", __apply_count];
  [ms appendString: @",invite_count:"];
  [ms appendFormat: @"%qi", __invite_count];
  [ms appendString: @",accept_count:"];
  [ms appendFormat: @"%qi", __accept_count];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation TaskExt

- (id) initWithApplied: (NSArray *) applied invited: (NSArray *) invited accepted: (NSArray *) accepted
{
  self = [super init];
  __applied = [applied retain];
  __applied_isset = YES;
  __invited = [invited retain];
  __invited_isset = YES;
  __accepted = [accepted retain];
  __accepted_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"applied"])
  {
    __applied = [[decoder decodeObjectForKey: @"applied"] retain];
    __applied_isset = YES;
  }
  if ([decoder containsValueForKey: @"invited"])
  {
    __invited = [[decoder decodeObjectForKey: @"invited"] retain];
    __invited_isset = YES;
  }
  if ([decoder containsValueForKey: @"accepted"])
  {
    __accepted = [[decoder decodeObjectForKey: @"accepted"] retain];
    __accepted_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__applied_isset)
  {
    [encoder encodeObject: __applied forKey: @"applied"];
  }
  if (__invited_isset)
  {
    [encoder encodeObject: __invited forKey: @"invited"];
  }
  if (__accepted_isset)
  {
    [encoder encodeObject: __accepted forKey: @"accepted"];
  }
}

- (void) dealloc
{
  [__applied release];
  [__invited release];
  [__accepted release];
  [super dealloc];
}

- (NSArray *) applied {
  return [[__applied retain] autorelease];
}

- (void) setApplied: (NSArray *) applied {
  [applied retain];
  [__applied release];
  __applied = applied;
  __applied_isset = YES;
}

- (BOOL) appliedIsSet {
  return __applied_isset;
}

- (void) unsetApplied {
  [__applied release];
  __applied = nil;
  __applied_isset = NO;
}

- (NSArray *) invited {
  return [[__invited retain] autorelease];
}

- (void) setInvited: (NSArray *) invited {
  [invited retain];
  [__invited release];
  __invited = invited;
  __invited_isset = YES;
}

- (BOOL) invitedIsSet {
  return __invited_isset;
}

- (void) unsetInvited {
  [__invited release];
  __invited = nil;
  __invited_isset = NO;
}

- (NSArray *) accepted {
  return [[__accepted retain] autorelease];
}

- (void) setAccepted: (NSArray *) accepted {
  [accepted retain];
  [__accepted release];
  __accepted = accepted;
  __accepted_isset = YES;
}

- (BOOL) acceptedIsSet {
  return __accepted_isset;
}

- (void) unsetAccepted {
  [__accepted release];
  __accepted = nil;
  __accepted_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_LIST) {
          int _size10;
          [inProtocol readListBeginReturningElementType: NULL size: &_size10];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size10];
          int _i11;
          for (_i11 = 0; _i11 < _size10; ++_i11)
          {
            int64_t _elem12 = [inProtocol readI64];
            [fieldValue addObject: [NSNumber numberWithLongLong: _elem12]];
          }
          [inProtocol readListEnd];
          [self setApplied: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_LIST) {
          int _size13;
          [inProtocol readListBeginReturningElementType: NULL size: &_size13];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size13];
          int _i14;
          for (_i14 = 0; _i14 < _size13; ++_i14)
          {
            int64_t _elem15 = [inProtocol readI64];
            [fieldValue addObject: [NSNumber numberWithLongLong: _elem15]];
          }
          [inProtocol readListEnd];
          [self setInvited: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_LIST) {
          int _size16;
          [inProtocol readListBeginReturningElementType: NULL size: &_size16];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size16];
          int _i17;
          for (_i17 = 0; _i17 < _size16; ++_i17)
          {
            int64_t _elem18 = [inProtocol readI64];
            [fieldValue addObject: [NSNumber numberWithLongLong: _elem18]];
          }
          [inProtocol readListEnd];
          [self setAccepted: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"TaskExt"];
  if (__applied_isset) {
    if (__applied != nil) {
      [outProtocol writeFieldBeginWithName: @"applied" type: TType_LIST fieldID: 1];
      {
        [outProtocol writeListBeginWithElementType: TType_I64 size: [__applied count]];
        int i20;
        for (i20 = 0; i20 < [__applied count]; i20++)
        {
          [outProtocol writeI64: [[__applied objectAtIndex: i20] longLongValue]];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  if (__invited_isset) {
    if (__invited != nil) {
      [outProtocol writeFieldBeginWithName: @"invited" type: TType_LIST fieldID: 2];
      {
        [outProtocol writeListBeginWithElementType: TType_I64 size: [__invited count]];
        int i22;
        for (i22 = 0; i22 < [__invited count]; i22++)
        {
          [outProtocol writeI64: [[__invited objectAtIndex: i22] longLongValue]];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  if (__accepted_isset) {
    if (__accepted != nil) {
      [outProtocol writeFieldBeginWithName: @"accepted" type: TType_LIST fieldID: 3];
      {
        [outProtocol writeListBeginWithElementType: TType_I64 size: [__accepted count]];
        int i24;
        for (i24 = 0; i24 < [__accepted count]; i24++)
        {
          [outProtocol writeI64: [[__accepted objectAtIndex: i24] longLongValue]];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"TaskExt("];
  [ms appendString: @"applied:"];
  [ms appendFormat: @"%@", __applied];
  [ms appendString: @",invited:"];
  [ms appendFormat: @"%@", __invited];
  [ms appendString: @",accepted:"];
  [ms appendFormat: @"%@", __accepted];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation Task

- (id) initWithBasic: (TaskBasic *) basic ext: (TaskExt *) ext
{
  self = [super init];
  __basic = [basic retain];
  __basic_isset = YES;
  __ext = [ext retain];
  __ext_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"basic"])
  {
    __basic = [[decoder decodeObjectForKey: @"basic"] retain];
    __basic_isset = YES;
  }
  if ([decoder containsValueForKey: @"ext"])
  {
    __ext = [[decoder decodeObjectForKey: @"ext"] retain];
    __ext_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__basic_isset)
  {
    [encoder encodeObject: __basic forKey: @"basic"];
  }
  if (__ext_isset)
  {
    [encoder encodeObject: __ext forKey: @"ext"];
  }
}

- (void) dealloc
{
  [__basic release];
  [__ext release];
  [super dealloc];
}

- (TaskBasic *) basic {
  return [[__basic retain] autorelease];
}

- (void) setBasic: (TaskBasic *) basic {
  [basic retain];
  [__basic release];
  __basic = basic;
  __basic_isset = YES;
}

- (BOOL) basicIsSet {
  return __basic_isset;
}

- (void) unsetBasic {
  [__basic release];
  __basic = nil;
  __basic_isset = NO;
}

- (TaskExt *) ext {
  return [[__ext retain] autorelease];
}

- (void) setExt: (TaskExt *) ext {
  [ext retain];
  [__ext release];
  __ext = ext;
  __ext_isset = YES;
}

- (BOOL) extIsSet {
  return __ext_isset;
}

- (void) unsetExt {
  [__ext release];
  __ext = nil;
  __ext_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          TaskBasic *fieldValue = [[TaskBasic alloc] init];
          [fieldValue read: inProtocol];
          [self setBasic: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRUCT) {
          TaskExt *fieldValue = [[TaskExt alloc] init];
          [fieldValue read: inProtocol];
          [self setExt: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Task"];
  if (__basic_isset) {
    if (__basic != nil) {
      [outProtocol writeFieldBeginWithName: @"basic" type: TType_STRUCT fieldID: 1];
      [__basic write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  if (__ext_isset) {
    if (__ext != nil) {
      [outProtocol writeFieldBeginWithName: @"ext" type: TType_STRUCT fieldID: 2];
      [__ext write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Task("];
  [ms appendString: @"basic:"];
  [ms appendFormat: @"%@", __basic];
  [ms appendString: @",ext:"];
  [ms appendFormat: @"%@", __ext];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation TaskListRequest

- (id) initWithLastid: (int64_t) lastid length: (int64_t) length type: (int) type
{
  self = [super init];
  __lastid = lastid;
  __lastid_isset = YES;
  __length = length;
  __length_isset = YES;
  __type = type;
  __type_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"lastid"])
  {
    __lastid = [decoder decodeInt64ForKey: @"lastid"];
    __lastid_isset = YES;
  }
  if ([decoder containsValueForKey: @"length"])
  {
    __length = [decoder decodeInt64ForKey: @"length"];
    __length_isset = YES;
  }
  if ([decoder containsValueForKey: @"type"])
  {
    __type = [decoder decodeIntForKey: @"type"];
    __type_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__lastid_isset)
  {
    [encoder encodeInt64: __lastid forKey: @"lastid"];
  }
  if (__length_isset)
  {
    [encoder encodeInt64: __length forKey: @"length"];
  }
  if (__type_isset)
  {
    [encoder encodeInt: __type forKey: @"type"];
  }
}

- (void) dealloc
{
  [super dealloc];
}

- (int64_t) lastid {
  return __lastid;
}

- (void) setLastid: (int64_t) lastid {
  __lastid = lastid;
  __lastid_isset = YES;
}

- (BOOL) lastidIsSet {
  return __lastid_isset;
}

- (void) unsetLastid {
  __lastid_isset = NO;
}

- (int64_t) length {
  return __length;
}

- (void) setLength: (int64_t) length {
  __length = length;
  __length_isset = YES;
}

- (BOOL) lengthIsSet {
  return __length_isset;
}

- (void) unsetLength {
  __length_isset = NO;
}

- (int) type {
  return __type;
}

- (void) setType: (int) type {
  __type = type;
  __type_isset = YES;
}

- (BOOL) typeIsSet {
  return __type_isset;
}

- (void) unsetType {
  __type_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setLastid: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setLength: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I32) {
          int fieldValue = [inProtocol readI32];
          [self setType: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"TaskListRequest"];
  if (__lastid_isset) {
    [outProtocol writeFieldBeginWithName: @"lastid" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __lastid];
    [outProtocol writeFieldEnd];
  }
  if (__length_isset) {
    [outProtocol writeFieldBeginWithName: @"length" type: TType_I64 fieldID: 2];
    [outProtocol writeI64: __length];
    [outProtocol writeFieldEnd];
  }
  if (__type_isset) {
    [outProtocol writeFieldBeginWithName: @"type" type: TType_I32 fieldID: 3];
    [outProtocol writeI32: __type];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"TaskListRequest("];
  [ms appendString: @"lastid:"];
  [ms appendFormat: @"%qi", __lastid];
  [ms appendString: @",length:"];
  [ms appendFormat: @"%qi", __length];
  [ms appendString: @",type:"];
  [ms appendFormat: @"%i", __type];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation Msg

- (id) initWithSender: (int64_t) sender time: (timestamp) time text: (NSString *) text type: (int) type
{
  self = [super init];
  __sender = sender;
  __sender_isset = YES;
  __time = time;
  __time_isset = YES;
  __text = [text retain];
  __text_isset = YES;
  __type = type;
  __type_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"sender"])
  {
    __sender = [decoder decodeInt64ForKey: @"sender"];
    __sender_isset = YES;
  }
  if ([decoder containsValueForKey: @"time"])
  {
    __time = [decoder decodeInt64ForKey: @"time"];
    __time_isset = YES;
  }
  if ([decoder containsValueForKey: @"text"])
  {
    __text = [[decoder decodeObjectForKey: @"text"] retain];
    __text_isset = YES;
  }
  if ([decoder containsValueForKey: @"type"])
  {
    __type = [decoder decodeIntForKey: @"type"];
    __type_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__sender_isset)
  {
    [encoder encodeInt64: __sender forKey: @"sender"];
  }
  if (__time_isset)
  {
    [encoder encodeInt64: __time forKey: @"time"];
  }
  if (__text_isset)
  {
    [encoder encodeObject: __text forKey: @"text"];
  }
  if (__type_isset)
  {
    [encoder encodeInt: __type forKey: @"type"];
  }
}

- (void) dealloc
{
  [__text release];
  [super dealloc];
}

- (int64_t) sender {
  return __sender;
}

- (void) setSender: (int64_t) sender {
  __sender = sender;
  __sender_isset = YES;
}

- (BOOL) senderIsSet {
  return __sender_isset;
}

- (void) unsetSender {
  __sender_isset = NO;
}

- (int64_t) time {
  return __time;
}

- (void) setTime: (int64_t) time {
  __time = time;
  __time_isset = YES;
}

- (BOOL) timeIsSet {
  return __time_isset;
}

- (void) unsetTime {
  __time_isset = NO;
}

- (NSString *) text {
  return [[__text retain] autorelease];
}

- (void) setText: (NSString *) text {
  [text retain];
  [__text release];
  __text = text;
  __text_isset = YES;
}

- (BOOL) textIsSet {
  return __text_isset;
}

- (void) unsetText {
  [__text release];
  __text = nil;
  __text_isset = NO;
}

- (int) type {
  return __type;
}

- (void) setType: (int) type {
  __type = type;
  __type_isset = YES;
}

- (BOOL) typeIsSet {
  return __type_isset;
}

- (void) unsetType {
  __type_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setSender: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setTime: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setText: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_I32) {
          int fieldValue = [inProtocol readI32];
          [self setType: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Msg"];
  if (__sender_isset) {
    [outProtocol writeFieldBeginWithName: @"sender" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __sender];
    [outProtocol writeFieldEnd];
  }
  if (__time_isset) {
    [outProtocol writeFieldBeginWithName: @"time" type: TType_I64 fieldID: 2];
    [outProtocol writeI64: __time];
    [outProtocol writeFieldEnd];
  }
  if (__text_isset) {
    if (__text != nil) {
      [outProtocol writeFieldBeginWithName: @"text" type: TType_STRING fieldID: 3];
      [outProtocol writeString: __text];
      [outProtocol writeFieldEnd];
    }
  }
  if (__type_isset) {
    [outProtocol writeFieldBeginWithName: @"type" type: TType_I32 fieldID: 4];
    [outProtocol writeI32: __type];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Msg("];
  [ms appendString: @"sender:"];
  [ms appendFormat: @"%qi", __sender];
  [ms appendString: @",time:"];
  [ms appendFormat: @"%qi", __time];
  [ms appendString: @",text:"];
  [ms appendFormat: @"\"%@\"", __text];
  [ms appendString: @",type:"];
  [ms appendFormat: @"%i", __type];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation FeedMsg

- (id) initWithSender: (NSString *) sender time: (timestamp) time type: (int) type content: (NSString *) content
{
  self = [super init];
  __sender = [sender retain];
  __sender_isset = YES;
  __time = time;
  __time_isset = YES;
  __type = type;
  __type_isset = YES;
  __content = [content retain];
  __content_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"sender"])
  {
    __sender = [[decoder decodeObjectForKey: @"sender"] retain];
    __sender_isset = YES;
  }
  if ([decoder containsValueForKey: @"time"])
  {
    __time = [decoder decodeInt64ForKey: @"time"];
    __time_isset = YES;
  }
  if ([decoder containsValueForKey: @"type"])
  {
    __type = [decoder decodeIntForKey: @"type"];
    __type_isset = YES;
  }
  if ([decoder containsValueForKey: @"content"])
  {
    __content = [[decoder decodeObjectForKey: @"content"] retain];
    __content_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__sender_isset)
  {
    [encoder encodeObject: __sender forKey: @"sender"];
  }
  if (__time_isset)
  {
    [encoder encodeInt64: __time forKey: @"time"];
  }
  if (__type_isset)
  {
    [encoder encodeInt: __type forKey: @"type"];
  }
  if (__content_isset)
  {
    [encoder encodeObject: __content forKey: @"content"];
  }
}

- (void) dealloc
{
  [__sender release];
  [__content release];
  [super dealloc];
}

- (NSString *) sender {
  return [[__sender retain] autorelease];
}

- (void) setSender: (NSString *) sender {
  [sender retain];
  [__sender release];
  __sender = sender;
  __sender_isset = YES;
}

- (BOOL) senderIsSet {
  return __sender_isset;
}

- (void) unsetSender {
  [__sender release];
  __sender = nil;
  __sender_isset = NO;
}

- (int64_t) time {
  return __time;
}

- (void) setTime: (int64_t) time {
  __time = time;
  __time_isset = YES;
}

- (BOOL) timeIsSet {
  return __time_isset;
}

- (void) unsetTime {
  __time_isset = NO;
}

- (int) type {
  return __type;
}

- (void) setType: (int) type {
  __type = type;
  __type_isset = YES;
}

- (BOOL) typeIsSet {
  return __type_isset;
}

- (void) unsetType {
  __type_isset = NO;
}

- (NSString *) content {
  return [[__content retain] autorelease];
}

- (void) setContent: (NSString *) content {
  [content retain];
  [__content release];
  __content = content;
  __content_isset = YES;
}

- (BOOL) contentIsSet {
  return __content_isset;
}

- (void) unsetContent {
  [__content release];
  __content = nil;
  __content_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setSender: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setTime: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I32) {
          int fieldValue = [inProtocol readI32];
          [self setType: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setContent: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"FeedMsg"];
  if (__sender_isset) {
    if (__sender != nil) {
      [outProtocol writeFieldBeginWithName: @"sender" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __sender];
      [outProtocol writeFieldEnd];
    }
  }
  if (__time_isset) {
    [outProtocol writeFieldBeginWithName: @"time" type: TType_I64 fieldID: 2];
    [outProtocol writeI64: __time];
    [outProtocol writeFieldEnd];
  }
  if (__type_isset) {
    [outProtocol writeFieldBeginWithName: @"type" type: TType_I32 fieldID: 3];
    [outProtocol writeI32: __type];
    [outProtocol writeFieldEnd];
  }
  if (__content_isset) {
    if (__content != nil) {
      [outProtocol writeFieldBeginWithName: @"content" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __content];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"FeedMsg("];
  [ms appendString: @"sender:"];
  [ms appendFormat: @"\"%@\"", __sender];
  [ms appendString: @",time:"];
  [ms appendFormat: @"%qi", __time];
  [ms appendString: @",type:"];
  [ms appendFormat: @"%i", __type];
  [ms appendString: @",content:"];
  [ms appendFormat: @"\"%@\"", __content];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation Summary

- (id) initWithUnread_msg_num: (int64_t) unread_msg_num following_num: (int64_t) following_num followed_num: (int64_t) followed_num
{
  self = [super init];
  __unread_msg_num = unread_msg_num;
  __unread_msg_num_isset = YES;
  __following_num = following_num;
  __following_num_isset = YES;
  __followed_num = followed_num;
  __followed_num_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"unread_msg_num"])
  {
    __unread_msg_num = [decoder decodeInt64ForKey: @"unread_msg_num"];
    __unread_msg_num_isset = YES;
  }
  if ([decoder containsValueForKey: @"following_num"])
  {
    __following_num = [decoder decodeInt64ForKey: @"following_num"];
    __following_num_isset = YES;
  }
  if ([decoder containsValueForKey: @"followed_num"])
  {
    __followed_num = [decoder decodeInt64ForKey: @"followed_num"];
    __followed_num_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__unread_msg_num_isset)
  {
    [encoder encodeInt64: __unread_msg_num forKey: @"unread_msg_num"];
  }
  if (__following_num_isset)
  {
    [encoder encodeInt64: __following_num forKey: @"following_num"];
  }
  if (__followed_num_isset)
  {
    [encoder encodeInt64: __followed_num forKey: @"followed_num"];
  }
}

- (void) dealloc
{
  [super dealloc];
}

- (int64_t) unread_msg_num {
  return __unread_msg_num;
}

- (void) setUnread_msg_num: (int64_t) unread_msg_num {
  __unread_msg_num = unread_msg_num;
  __unread_msg_num_isset = YES;
}

- (BOOL) unread_msg_numIsSet {
  return __unread_msg_num_isset;
}

- (void) unsetUnread_msg_num {
  __unread_msg_num_isset = NO;
}

- (int64_t) following_num {
  return __following_num;
}

- (void) setFollowing_num: (int64_t) following_num {
  __following_num = following_num;
  __following_num_isset = YES;
}

- (BOOL) following_numIsSet {
  return __following_num_isset;
}

- (void) unsetFollowing_num {
  __following_num_isset = NO;
}

- (int64_t) followed_num {
  return __followed_num;
}

- (void) setFollowed_num: (int64_t) followed_num {
  __followed_num = followed_num;
  __followed_num_isset = YES;
}

- (BOOL) followed_numIsSet {
  return __followed_num_isset;
}

- (void) unsetFollowed_num {
  __followed_num_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setUnread_msg_num: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setFollowing_num: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setFollowed_num: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Summary"];
  if (__unread_msg_num_isset) {
    [outProtocol writeFieldBeginWithName: @"unread_msg_num" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __unread_msg_num];
    [outProtocol writeFieldEnd];
  }
  if (__following_num_isset) {
    [outProtocol writeFieldBeginWithName: @"following_num" type: TType_I64 fieldID: 2];
    [outProtocol writeI64: __following_num];
    [outProtocol writeFieldEnd];
  }
  if (__followed_num_isset) {
    [outProtocol writeFieldBeginWithName: @"followed_num" type: TType_I64 fieldID: 3];
    [outProtocol writeI64: __followed_num];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Summary("];
  [ms appendString: @"unread_msg_num:"];
  [ms appendFormat: @"%qi", __unread_msg_num];
  [ms appendString: @",following_num:"];
  [ms appendFormat: @"%qi", __following_num];
  [ms appendString: @",followed_num:"];
  [ms appendFormat: @"%qi", __followed_num];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end


@implementation typeConstants
+ (void) initialize {
}
@end

